test: 
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  database: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  username: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  password: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
