default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: 172.17.0.1
  username: postgres
  password: postgres

development:
  <<: *default
  database: flau_produttivo_app_developer

test:
  <<: *default
  database: flau_produttivo_app_test

production:
  <<: *default
  database: flau_produttivo_app_prod